version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_greenfood
    image: postgres:12.2
    environment:
      POSTGRES_USER: greenfood
      POSTGRES_PASSWORD: greenfood
    ports:
      - "5432:5432"